package org.exam.bean.entity;

/**
 * Database Table Remarks:
 *   学院表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_academy
 *
 * @mbg.generated do_not_delete_during_merge Fri Mar 29 23:04:33 CST 2019
 */
public class TAcademy {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.id
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   学院编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.academy_no
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    private Long academyNo;

    /**
     * Database Column Remarks:
     *   学院名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.academy_name
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    private String academyName;

    /**
     * Database Column Remarks:
     *   删除标识：0-未删除；1-已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.is_del
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    private byte[] isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.create_time
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    private Long createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.update_time
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    private Long updateTime;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.creater
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    private Integer creater;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.updater
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    private Integer updater;

    /**
     * Database Column Remarks:
     *   版本号，乐观锁专用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_academy.version
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.id
     *
     * @return the value of t_academy.id
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.id
     *
     * @param id the value for t_academy.id
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.academy_no
     *
     * @return the value of t_academy.academy_no
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public Long getAcademyNo() {
        return academyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.academy_no
     *
     * @param academyNo the value for t_academy.academy_no
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public void setAcademyNo(Long academyNo) {
        this.academyNo = academyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.academy_name
     *
     * @return the value of t_academy.academy_name
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public String getAcademyName() {
        return academyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.academy_name
     *
     * @param academyName the value for t_academy.academy_name
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public void setAcademyName(String academyName) {
        this.academyName = academyName == null ? null : academyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.is_del
     *
     * @return the value of t_academy.is_del
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public byte[] getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.is_del
     *
     * @param isDel the value for t_academy.is_del
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public void setIsDel(byte[] isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.create_time
     *
     * @return the value of t_academy.create_time
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.create_time
     *
     * @param createTime the value for t_academy.create_time
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.update_time
     *
     * @return the value of t_academy.update_time
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.update_time
     *
     * @param updateTime the value for t_academy.update_time
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.creater
     *
     * @return the value of t_academy.creater
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public Integer getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.creater
     *
     * @param creater the value for t_academy.creater
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public void setCreater(Integer creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.updater
     *
     * @return the value of t_academy.updater
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public Integer getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.updater
     *
     * @param updater the value for t_academy.updater
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_academy.version
     *
     * @return the value of t_academy.version
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_academy.version
     *
     * @param version the value for t_academy.version
     *
     * @mbg.generated Fri Mar 29 23:04:33 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}