package org.exam.bean.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;

/**
 * Database Table Remarks:
 *   专业表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_major
 *
 * @mbg.generated do_not_delete_during_merge Wed Apr 03 11:42:34 CST 2019
 */
public class TMajor {
    @Getter
    @Setter
    private TAcademy academy;
    /**
     * Database Column Remarks:
     *   专业编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.major_id
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    @JsonSerialize(using = ToStringSerializer.class)
    private Long majorId;

    /**
     * Database Column Remarks:
     *   专业名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.major_name
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    private String majorName;

    /**
     * Database Column Remarks:
     *   学院id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.academy_id
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    @JsonSerialize(using = ToStringSerializer.class)
    private Long academyId;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.creator
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    private Long creator;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.updater
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    private Long updater;

    /**
     * Database Column Remarks:
     *   版本号，乐观锁专用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.version
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    private Integer version;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.is_del
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.create_time
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_major.update_time
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.major_id
     *
     * @return the value of t_major.major_id
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public Long getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.major_id
     *
     * @param majorId the value for t_major.major_id
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public void setMajorId(Long majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.major_name
     *
     * @return the value of t_major.major_name
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.major_name
     *
     * @param majorName the value for t_major.major_name
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.academy_id
     *
     * @return the value of t_major.academy_id
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public Long getAcademyId() {
        return academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.academy_id
     *
     * @param academyId the value for t_major.academy_id
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public void setAcademyId(Long academyId) {
        this.academyId = academyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.creator
     *
     * @return the value of t_major.creator
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.creator
     *
     * @param creator the value for t_major.creator
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.updater
     *
     * @return the value of t_major.updater
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.updater
     *
     * @param updater the value for t_major.updater
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.version
     *
     * @return the value of t_major.version
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.version
     *
     * @param version the value for t_major.version
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.is_del
     *
     * @return the value of t_major.is_del
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.is_del
     *
     * @param isDel the value for t_major.is_del
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.create_time
     *
     * @return the value of t_major.create_time
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.create_time
     *
     * @param createTime the value for t_major.create_time
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_major.update_time
     *
     * @return the value of t_major.update_time
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_major.update_time
     *
     * @param updateTime the value for t_major.update_time
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}