package org.exam.bean.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TQuestionChoiceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    public TQuestionChoiceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChoiceIdIsNull() {
            addCriterion("choice_id is null");
            return (Criteria) this;
        }

        public Criteria andChoiceIdIsNotNull() {
            addCriterion("choice_id is not null");
            return (Criteria) this;
        }

        public Criteria andChoiceIdEqualTo(Long value) {
            addCriterion("choice_id =", value, "choiceId");
            return (Criteria) this;
        }

        public Criteria andChoiceIdNotEqualTo(Long value) {
            addCriterion("choice_id <>", value, "choiceId");
            return (Criteria) this;
        }

        public Criteria andChoiceIdGreaterThan(Long value) {
            addCriterion("choice_id >", value, "choiceId");
            return (Criteria) this;
        }

        public Criteria andChoiceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("choice_id >=", value, "choiceId");
            return (Criteria) this;
        }

        public Criteria andChoiceIdLessThan(Long value) {
            addCriterion("choice_id <", value, "choiceId");
            return (Criteria) this;
        }

        public Criteria andChoiceIdLessThanOrEqualTo(Long value) {
            addCriterion("choice_id <=", value, "choiceId");
            return (Criteria) this;
        }

        public Criteria andChoiceIdIn(List<Long> values) {
            addCriterion("choice_id in", values, "choiceId");
            return (Criteria) this;
        }

        public Criteria andChoiceIdNotIn(List<Long> values) {
            addCriterion("choice_id not in", values, "choiceId");
            return (Criteria) this;
        }

        public Criteria andChoiceIdBetween(Long value1, Long value2) {
            addCriterion("choice_id between", value1, value2, "choiceId");
            return (Criteria) this;
        }

        public Criteria andChoiceIdNotBetween(Long value1, Long value2) {
            addCriterion("choice_id not between", value1, value2, "choiceId");
            return (Criteria) this;
        }

        public Criteria andChoiceNameIsNull() {
            addCriterion("choice_name is null");
            return (Criteria) this;
        }

        public Criteria andChoiceNameIsNotNull() {
            addCriterion("choice_name is not null");
            return (Criteria) this;
        }

        public Criteria andChoiceNameEqualTo(String value) {
            addCriterion("choice_name =", value, "choiceName");
            return (Criteria) this;
        }

        public Criteria andChoiceNameNotEqualTo(String value) {
            addCriterion("choice_name <>", value, "choiceName");
            return (Criteria) this;
        }

        public Criteria andChoiceNameGreaterThan(String value) {
            addCriterion("choice_name >", value, "choiceName");
            return (Criteria) this;
        }

        public Criteria andChoiceNameGreaterThanOrEqualTo(String value) {
            addCriterion("choice_name >=", value, "choiceName");
            return (Criteria) this;
        }

        public Criteria andChoiceNameLessThan(String value) {
            addCriterion("choice_name <", value, "choiceName");
            return (Criteria) this;
        }

        public Criteria andChoiceNameLessThanOrEqualTo(String value) {
            addCriterion("choice_name <=", value, "choiceName");
            return (Criteria) this;
        }

        public Criteria andChoiceNameLike(String value) {
            addCriterion("choice_name like", value, "choiceName");
            return (Criteria) this;
        }

        public Criteria andChoiceNameNotLike(String value) {
            addCriterion("choice_name not like", value, "choiceName");
            return (Criteria) this;
        }

        public Criteria andChoiceNameIn(List<String> values) {
            addCriterion("choice_name in", values, "choiceName");
            return (Criteria) this;
        }

        public Criteria andChoiceNameNotIn(List<String> values) {
            addCriterion("choice_name not in", values, "choiceName");
            return (Criteria) this;
        }

        public Criteria andChoiceNameBetween(String value1, String value2) {
            addCriterion("choice_name between", value1, value2, "choiceName");
            return (Criteria) this;
        }

        public Criteria andChoiceNameNotBetween(String value1, String value2) {
            addCriterion("choice_name not between", value1, value2, "choiceName");
            return (Criteria) this;
        }

        public Criteria andChoiceTypeIsNull() {
            addCriterion("choice_type is null");
            return (Criteria) this;
        }

        public Criteria andChoiceTypeIsNotNull() {
            addCriterion("choice_type is not null");
            return (Criteria) this;
        }

        public Criteria andChoiceTypeEqualTo(Boolean value) {
            addCriterion("choice_type =", value, "choiceType");
            return (Criteria) this;
        }

        public Criteria andChoiceTypeNotEqualTo(Boolean value) {
            addCriterion("choice_type <>", value, "choiceType");
            return (Criteria) this;
        }

        public Criteria andChoiceTypeGreaterThan(Boolean value) {
            addCriterion("choice_type >", value, "choiceType");
            return (Criteria) this;
        }

        public Criteria andChoiceTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("choice_type >=", value, "choiceType");
            return (Criteria) this;
        }

        public Criteria andChoiceTypeLessThan(Boolean value) {
            addCriterion("choice_type <", value, "choiceType");
            return (Criteria) this;
        }

        public Criteria andChoiceTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("choice_type <=", value, "choiceType");
            return (Criteria) this;
        }

        public Criteria andChoiceTypeIn(List<Boolean> values) {
            addCriterion("choice_type in", values, "choiceType");
            return (Criteria) this;
        }

        public Criteria andChoiceTypeNotIn(List<Boolean> values) {
            addCriterion("choice_type not in", values, "choiceType");
            return (Criteria) this;
        }

        public Criteria andChoiceTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("choice_type between", value1, value2, "choiceType");
            return (Criteria) this;
        }

        public Criteria andChoiceTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("choice_type not between", value1, value2, "choiceType");
            return (Criteria) this;
        }

        public Criteria andOptionAIsNull() {
            addCriterion("option_a is null");
            return (Criteria) this;
        }

        public Criteria andOptionAIsNotNull() {
            addCriterion("option_a is not null");
            return (Criteria) this;
        }

        public Criteria andOptionAEqualTo(String value) {
            addCriterion("option_a =", value, "optionA");
            return (Criteria) this;
        }

        public Criteria andOptionANotEqualTo(String value) {
            addCriterion("option_a <>", value, "optionA");
            return (Criteria) this;
        }

        public Criteria andOptionAGreaterThan(String value) {
            addCriterion("option_a >", value, "optionA");
            return (Criteria) this;
        }

        public Criteria andOptionAGreaterThanOrEqualTo(String value) {
            addCriterion("option_a >=", value, "optionA");
            return (Criteria) this;
        }

        public Criteria andOptionALessThan(String value) {
            addCriterion("option_a <", value, "optionA");
            return (Criteria) this;
        }

        public Criteria andOptionALessThanOrEqualTo(String value) {
            addCriterion("option_a <=", value, "optionA");
            return (Criteria) this;
        }

        public Criteria andOptionALike(String value) {
            addCriterion("option_a like", value, "optionA");
            return (Criteria) this;
        }

        public Criteria andOptionANotLike(String value) {
            addCriterion("option_a not like", value, "optionA");
            return (Criteria) this;
        }

        public Criteria andOptionAIn(List<String> values) {
            addCriterion("option_a in", values, "optionA");
            return (Criteria) this;
        }

        public Criteria andOptionANotIn(List<String> values) {
            addCriterion("option_a not in", values, "optionA");
            return (Criteria) this;
        }

        public Criteria andOptionABetween(String value1, String value2) {
            addCriterion("option_a between", value1, value2, "optionA");
            return (Criteria) this;
        }

        public Criteria andOptionANotBetween(String value1, String value2) {
            addCriterion("option_a not between", value1, value2, "optionA");
            return (Criteria) this;
        }

        public Criteria andOptionBIsNull() {
            addCriterion("option_b is null");
            return (Criteria) this;
        }

        public Criteria andOptionBIsNotNull() {
            addCriterion("option_b is not null");
            return (Criteria) this;
        }

        public Criteria andOptionBEqualTo(String value) {
            addCriterion("option_b =", value, "optionB");
            return (Criteria) this;
        }

        public Criteria andOptionBNotEqualTo(String value) {
            addCriterion("option_b <>", value, "optionB");
            return (Criteria) this;
        }

        public Criteria andOptionBGreaterThan(String value) {
            addCriterion("option_b >", value, "optionB");
            return (Criteria) this;
        }

        public Criteria andOptionBGreaterThanOrEqualTo(String value) {
            addCriterion("option_b >=", value, "optionB");
            return (Criteria) this;
        }

        public Criteria andOptionBLessThan(String value) {
            addCriterion("option_b <", value, "optionB");
            return (Criteria) this;
        }

        public Criteria andOptionBLessThanOrEqualTo(String value) {
            addCriterion("option_b <=", value, "optionB");
            return (Criteria) this;
        }

        public Criteria andOptionBLike(String value) {
            addCriterion("option_b like", value, "optionB");
            return (Criteria) this;
        }

        public Criteria andOptionBNotLike(String value) {
            addCriterion("option_b not like", value, "optionB");
            return (Criteria) this;
        }

        public Criteria andOptionBIn(List<String> values) {
            addCriterion("option_b in", values, "optionB");
            return (Criteria) this;
        }

        public Criteria andOptionBNotIn(List<String> values) {
            addCriterion("option_b not in", values, "optionB");
            return (Criteria) this;
        }

        public Criteria andOptionBBetween(String value1, String value2) {
            addCriterion("option_b between", value1, value2, "optionB");
            return (Criteria) this;
        }

        public Criteria andOptionBNotBetween(String value1, String value2) {
            addCriterion("option_b not between", value1, value2, "optionB");
            return (Criteria) this;
        }

        public Criteria andOptionCIsNull() {
            addCriterion("option_c is null");
            return (Criteria) this;
        }

        public Criteria andOptionCIsNotNull() {
            addCriterion("option_c is not null");
            return (Criteria) this;
        }

        public Criteria andOptionCEqualTo(String value) {
            addCriterion("option_c =", value, "optionC");
            return (Criteria) this;
        }

        public Criteria andOptionCNotEqualTo(String value) {
            addCriterion("option_c <>", value, "optionC");
            return (Criteria) this;
        }

        public Criteria andOptionCGreaterThan(String value) {
            addCriterion("option_c >", value, "optionC");
            return (Criteria) this;
        }

        public Criteria andOptionCGreaterThanOrEqualTo(String value) {
            addCriterion("option_c >=", value, "optionC");
            return (Criteria) this;
        }

        public Criteria andOptionCLessThan(String value) {
            addCriterion("option_c <", value, "optionC");
            return (Criteria) this;
        }

        public Criteria andOptionCLessThanOrEqualTo(String value) {
            addCriterion("option_c <=", value, "optionC");
            return (Criteria) this;
        }

        public Criteria andOptionCLike(String value) {
            addCriterion("option_c like", value, "optionC");
            return (Criteria) this;
        }

        public Criteria andOptionCNotLike(String value) {
            addCriterion("option_c not like", value, "optionC");
            return (Criteria) this;
        }

        public Criteria andOptionCIn(List<String> values) {
            addCriterion("option_c in", values, "optionC");
            return (Criteria) this;
        }

        public Criteria andOptionCNotIn(List<String> values) {
            addCriterion("option_c not in", values, "optionC");
            return (Criteria) this;
        }

        public Criteria andOptionCBetween(String value1, String value2) {
            addCriterion("option_c between", value1, value2, "optionC");
            return (Criteria) this;
        }

        public Criteria andOptionCNotBetween(String value1, String value2) {
            addCriterion("option_c not between", value1, value2, "optionC");
            return (Criteria) this;
        }

        public Criteria andOptionDIsNull() {
            addCriterion("option_d is null");
            return (Criteria) this;
        }

        public Criteria andOptionDIsNotNull() {
            addCriterion("option_d is not null");
            return (Criteria) this;
        }

        public Criteria andOptionDEqualTo(String value) {
            addCriterion("option_d =", value, "optionD");
            return (Criteria) this;
        }

        public Criteria andOptionDNotEqualTo(String value) {
            addCriterion("option_d <>", value, "optionD");
            return (Criteria) this;
        }

        public Criteria andOptionDGreaterThan(String value) {
            addCriterion("option_d >", value, "optionD");
            return (Criteria) this;
        }

        public Criteria andOptionDGreaterThanOrEqualTo(String value) {
            addCriterion("option_d >=", value, "optionD");
            return (Criteria) this;
        }

        public Criteria andOptionDLessThan(String value) {
            addCriterion("option_d <", value, "optionD");
            return (Criteria) this;
        }

        public Criteria andOptionDLessThanOrEqualTo(String value) {
            addCriterion("option_d <=", value, "optionD");
            return (Criteria) this;
        }

        public Criteria andOptionDLike(String value) {
            addCriterion("option_d like", value, "optionD");
            return (Criteria) this;
        }

        public Criteria andOptionDNotLike(String value) {
            addCriterion("option_d not like", value, "optionD");
            return (Criteria) this;
        }

        public Criteria andOptionDIn(List<String> values) {
            addCriterion("option_d in", values, "optionD");
            return (Criteria) this;
        }

        public Criteria andOptionDNotIn(List<String> values) {
            addCriterion("option_d not in", values, "optionD");
            return (Criteria) this;
        }

        public Criteria andOptionDBetween(String value1, String value2) {
            addCriterion("option_d between", value1, value2, "optionD");
            return (Criteria) this;
        }

        public Criteria andOptionDNotBetween(String value1, String value2) {
            addCriterion("option_d not between", value1, value2, "optionD");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIsNull() {
            addCriterion("single_answer is null");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIsNotNull() {
            addCriterion("single_answer is not null");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerEqualTo(String value) {
            addCriterion("single_answer =", value, "singleAnswer");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerNotEqualTo(String value) {
            addCriterion("single_answer <>", value, "singleAnswer");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerGreaterThan(String value) {
            addCriterion("single_answer >", value, "singleAnswer");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("single_answer >=", value, "singleAnswer");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerLessThan(String value) {
            addCriterion("single_answer <", value, "singleAnswer");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerLessThanOrEqualTo(String value) {
            addCriterion("single_answer <=", value, "singleAnswer");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerLike(String value) {
            addCriterion("single_answer like", value, "singleAnswer");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerNotLike(String value) {
            addCriterion("single_answer not like", value, "singleAnswer");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerIn(List<String> values) {
            addCriterion("single_answer in", values, "singleAnswer");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerNotIn(List<String> values) {
            addCriterion("single_answer not in", values, "singleAnswer");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerBetween(String value1, String value2) {
            addCriterion("single_answer between", value1, value2, "singleAnswer");
            return (Criteria) this;
        }

        public Criteria andSingleAnswerNotBetween(String value1, String value2) {
            addCriterion("single_answer not between", value1, value2, "singleAnswer");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerIsNull() {
            addCriterion("multi_answer is null");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerIsNotNull() {
            addCriterion("multi_answer is not null");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerEqualTo(String value) {
            addCriterion("multi_answer =", value, "multiAnswer");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerNotEqualTo(String value) {
            addCriterion("multi_answer <>", value, "multiAnswer");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerGreaterThan(String value) {
            addCriterion("multi_answer >", value, "multiAnswer");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("multi_answer >=", value, "multiAnswer");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerLessThan(String value) {
            addCriterion("multi_answer <", value, "multiAnswer");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerLessThanOrEqualTo(String value) {
            addCriterion("multi_answer <=", value, "multiAnswer");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerLike(String value) {
            addCriterion("multi_answer like", value, "multiAnswer");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerNotLike(String value) {
            addCriterion("multi_answer not like", value, "multiAnswer");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerIn(List<String> values) {
            addCriterion("multi_answer in", values, "multiAnswer");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerNotIn(List<String> values) {
            addCriterion("multi_answer not in", values, "multiAnswer");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerBetween(String value1, String value2) {
            addCriterion("multi_answer between", value1, value2, "multiAnswer");
            return (Criteria) this;
        }

        public Criteria andMultiAnswerNotBetween(String value1, String value2) {
            addCriterion("multi_answer not between", value1, value2, "multiAnswer");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNull() {
            addCriterion("course_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNotNull() {
            addCriterion("course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseIdEqualTo(Long value) {
            addCriterion("course_id =", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotEqualTo(Long value) {
            addCriterion("course_id <>", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThan(Long value) {
            addCriterion("course_id >", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("course_id >=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThan(Long value) {
            addCriterion("course_id <", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThanOrEqualTo(Long value) {
            addCriterion("course_id <=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIn(List<Long> values) {
            addCriterion("course_id in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotIn(List<Long> values) {
            addCriterion("course_id not in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdBetween(Long value1, Long value2) {
            addCriterion("course_id between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotBetween(Long value1, Long value2) {
            addCriterion("course_id not between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Boolean value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Boolean value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Boolean value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Boolean value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Boolean value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Boolean> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Boolean> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Boolean value1, Boolean value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Integer value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Integer value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Integer value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Integer value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Integer value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Integer> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Integer> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Integer value1, Integer value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Integer value1, Integer value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(Integer value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(Integer value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(Integer value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(Integer value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(Integer value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(Integer value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<Integer> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<Integer> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(Integer value1, Integer value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(Integer value1, Integer value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_question_choice
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 04 09:18:06 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_question_choice
     *
     * @mbg.generated Thu Apr 04 09:18:06 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}