package org.exam.bean.entity;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;

import java.util.Date;

/**
 * Database Table Remarks:
 *   判断题
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_question_judge
 *
 * @mbg.generated do_not_delete_during_merge Thu Apr 04 09:19:16 CST 2019
 */
public class TQuestionJudge {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_judge.judge_id
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    @JsonSerialize(using = ToStringSerializer.class)
    private Long judgeId;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_judge.judge_name
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    private String judgeName;

    /**
     * Database Column Remarks:
     *   答案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_judge.answer
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    private Boolean answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_judge.course_id
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    @JsonSerialize(using = ToStringSerializer.class)
    private Long courseId;

    /**
     * Database Column Remarks:
     *   删除标识：0-未删除；1-已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_judge.is_del
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_judge.create_time
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_judge.update_time
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_judge.creator
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    private Long creator;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_judge.updater
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    private Long updater;

    /**
     * Database Column Remarks:
     *   版本号，乐观锁专用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question_judge.version
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_judge.judge_id
     *
     * @return the value of t_question_judge.judge_id
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public Long getJudgeId() {
        return judgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_judge.judge_id
     *
     * @param judgeId the value for t_question_judge.judge_id
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public void setJudgeId(Long judgeId) {
        this.judgeId = judgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_judge.judge_name
     *
     * @return the value of t_question_judge.judge_name
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public String getJudgeName() {
        return judgeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_judge.judge_name
     *
     * @param judgeName the value for t_question_judge.judge_name
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public void setJudgeName(String judgeName) {
        this.judgeName = judgeName == null ? null : judgeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_judge.answer
     *
     * @return the value of t_question_judge.answer
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public Boolean getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_judge.answer
     *
     * @param answer the value for t_question_judge.answer
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public void setAnswer(Boolean answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_judge.course_id
     *
     * @return the value of t_question_judge.course_id
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_judge.course_id
     *
     * @param courseId the value for t_question_judge.course_id
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_judge.is_del
     *
     * @return the value of t_question_judge.is_del
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_judge.is_del
     *
     * @param isDel the value for t_question_judge.is_del
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_judge.create_time
     *
     * @return the value of t_question_judge.create_time
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_judge.create_time
     *
     * @param createTime the value for t_question_judge.create_time
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_judge.update_time
     *
     * @return the value of t_question_judge.update_time
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_judge.update_time
     *
     * @param updateTime the value for t_question_judge.update_time
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_judge.creator
     *
     * @return the value of t_question_judge.creator
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_judge.creator
     *
     * @param creator the value for t_question_judge.creator
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_judge.updater
     *
     * @return the value of t_question_judge.updater
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_judge.updater
     *
     * @param updater the value for t_question_judge.updater
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question_judge.version
     *
     * @return the value of t_question_judge.version
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question_judge.version
     *
     * @param version the value for t_question_judge.version
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}