package org.exam.bean.entity;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户课程关系表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user_clazz_course
 *
 * @mbg.generated do_not_delete_during_merge Thu Apr 04 09:15:24 CST 2019
 */
public class TUserClazzCourse {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_clazz_course.id
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    @JsonSerialize(using = ToStringSerializer.class)
    private Long id;

    /**
     * Database Column Remarks:
     *   班级id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_clazz_course.clazz_id
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    @JsonSerialize(using = ToStringSerializer.class)
    private Long clazzId;

    /**
     * Database Column Remarks:
     *   课程id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_clazz_course.course_id
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    @JsonSerialize(using = ToStringSerializer.class)
    private Long courseId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_clazz_course.user_id
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    @JsonSerialize(using = ToStringSerializer.class)
    private Long userId;

    /**
     * Database Column Remarks:
     *   删除标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_clazz_course.is_del
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_clazz_course.create_time
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_clazz_course.update_time
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_clazz_course.creator
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    private Integer creator;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_clazz_course.updater
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    private Integer updater;

    /**
     * Database Column Remarks:
     *   版本号，乐观锁专用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_clazz_course.version
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_clazz_course.id
     *
     * @return the value of t_user_clazz_course.id
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_clazz_course.id
     *
     * @param id the value for t_user_clazz_course.id
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_clazz_course.clazz_id
     *
     * @return the value of t_user_clazz_course.clazz_id
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public Long getClazzId() {
        return clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_clazz_course.clazz_id
     *
     * @param clazzId the value for t_user_clazz_course.clazz_id
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public void setClazzId(Long clazzId) {
        this.clazzId = clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_clazz_course.course_id
     *
     * @return the value of t_user_clazz_course.course_id
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_clazz_course.course_id
     *
     * @param courseId the value for t_user_clazz_course.course_id
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_clazz_course.user_id
     *
     * @return the value of t_user_clazz_course.user_id
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_clazz_course.user_id
     *
     * @param userId the value for t_user_clazz_course.user_id
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_clazz_course.is_del
     *
     * @return the value of t_user_clazz_course.is_del
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_clazz_course.is_del
     *
     * @param isDel the value for t_user_clazz_course.is_del
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_clazz_course.create_time
     *
     * @return the value of t_user_clazz_course.create_time
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_clazz_course.create_time
     *
     * @param createTime the value for t_user_clazz_course.create_time
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_clazz_course.update_time
     *
     * @return the value of t_user_clazz_course.update_time
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_clazz_course.update_time
     *
     * @param updateTime the value for t_user_clazz_course.update_time
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_clazz_course.creator
     *
     * @return the value of t_user_clazz_course.creator
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_clazz_course.creator
     *
     * @param creator the value for t_user_clazz_course.creator
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_clazz_course.updater
     *
     * @return the value of t_user_clazz_course.updater
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public Integer getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_clazz_course.updater
     *
     * @param updater the value for t_user_clazz_course.updater
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_clazz_course.version
     *
     * @return the value of t_user_clazz_course.version
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_clazz_course.version
     *
     * @param version the value for t_user_clazz_course.version
     *
     * @mbg.generated Thu Apr 04 09:15:24 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}