package org.exam.bean.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user
 *
 * @mbg.generated do_not_delete_during_merge Sat Mar 30 22:51:53 CST 2019
 */
public class TUser {
    /**
     * Database Column Remarks:
     *   用户id，分布式id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private String name;

    /**
     * Database Column Remarks:
     *   手机号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.mobile_phone
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private String mobilePhone;

    /**
     * Database Column Remarks:
     *   住宅电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.telephone
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private String telephone;

    /**
     * Database Column Remarks:
     *   联系地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.address
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private String address;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private String password;

    /**
     * Database Column Remarks:
     *   性别：1-男；2-女；0-保密，关联字典表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.sex
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private String sex;

    /**
     * Database Column Remarks:
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id_card
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private String idCard;

    /**
     * Database Column Remarks:
     *   民族
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.nation_id
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private Long nationId;

    /**
     * Database Column Remarks:
     *   用户图像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_face
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private String userFace;

    /**
     * Database Column Remarks:
     *   婚姻状况：1-已婚；2-未婚；3-离异,关联字典表主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.marital_status
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private Long maritalStatus;

    /**
     * Database Column Remarks:
     *   籍贯
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.native_place
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private String nativePlace;

    /**
     * Database Column Remarks:
     *   出生日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.birthday
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private Long birthday;

    /**
     * Database Column Remarks:
     *   电子邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private String email;

    /**
     * Database Column Remarks:
     *   入学日期：学生专用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.enrollment_date
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private Long enrollmentDate;

    /**
     * Database Column Remarks:
     *   毕业日期：学生专用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.graduation_date
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private Long graduationDate;

    /**
     * Database Column Remarks:
     *   删除标识：0-未删除；1-已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.is_del
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.create_time
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.update_time
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.creator
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private Long creator;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.updater
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private Long updater;

    /**
     * Database Column Remarks:
     *   版本号，乐观锁专用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.version
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.name
     *
     * @return the value of t_user.name
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.name
     *
     * @param name the value for t_user.name
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.mobile_phone
     *
     * @return the value of t_user.mobile_phone
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.mobile_phone
     *
     * @param mobilePhone the value for t_user.mobile_phone
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.telephone
     *
     * @return the value of t_user.telephone
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.telephone
     *
     * @param telephone the value for t_user.telephone
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.address
     *
     * @return the value of t_user.address
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.address
     *
     * @param address the value for t_user.address
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.sex
     *
     * @return the value of t_user.sex
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.sex
     *
     * @param sex the value for t_user.sex
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id_card
     *
     * @return the value of t_user.id_card
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id_card
     *
     * @param idCard the value for t_user.id_card
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.nation_id
     *
     * @return the value of t_user.nation_id
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public Long getNationId() {
        return nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.nation_id
     *
     * @param nationId the value for t_user.nation_id
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setNationId(Long nationId) {
        this.nationId = nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_face
     *
     * @return the value of t_user.user_face
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public String getUserFace() {
        return userFace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_face
     *
     * @param userFace the value for t_user.user_face
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setUserFace(String userFace) {
        this.userFace = userFace == null ? null : userFace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.marital_status
     *
     * @return the value of t_user.marital_status
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public Long getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.marital_status
     *
     * @param maritalStatus the value for t_user.marital_status
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setMaritalStatus(Long maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.native_place
     *
     * @return the value of t_user.native_place
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.native_place
     *
     * @param nativePlace the value for t_user.native_place
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace == null ? null : nativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.birthday
     *
     * @return the value of t_user.birthday
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public Long getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.birthday
     *
     * @param birthday the value for t_user.birthday
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.enrollment_date
     *
     * @return the value of t_user.enrollment_date
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public Long getEnrollmentDate() {
        return enrollmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.enrollment_date
     *
     * @param enrollmentDate the value for t_user.enrollment_date
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setEnrollmentDate(Long enrollmentDate) {
        this.enrollmentDate = enrollmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.graduation_date
     *
     * @return the value of t_user.graduation_date
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public Long getGraduationDate() {
        return graduationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.graduation_date
     *
     * @param graduationDate the value for t_user.graduation_date
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setGraduationDate(Long graduationDate) {
        this.graduationDate = graduationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.is_del
     *
     * @return the value of t_user.is_del
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.is_del
     *
     * @param isDel the value for t_user.is_del
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.create_time
     *
     * @return the value of t_user.create_time
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.create_time
     *
     * @param createTime the value for t_user.create_time
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.update_time
     *
     * @return the value of t_user.update_time
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.update_time
     *
     * @param updateTime the value for t_user.update_time
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.creator
     *
     * @return the value of t_user.creator
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.creator
     *
     * @param creator the value for t_user.creator
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.updater
     *
     * @return the value of t_user.updater
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.updater
     *
     * @param updater the value for t_user.updater
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.version
     *
     * @return the value of t_user.version
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.version
     *
     * @param version the value for t_user.version
     *
     * @mbg.generated Sat Mar 30 22:51:53 CST 2019
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}