package org.exam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.exam.bean.entity.TClazz;
import org.exam.bean.entity.TClazzExample;

public interface TClazzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated Wed Apr 03 11:50:58 CST 2019
     */
    long countByExample(TClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated Wed Apr 03 11:50:58 CST 2019
     */
    int deleteByExample(TClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated Wed Apr 03 11:50:58 CST 2019
     */
    @Delete({
        "delete from t_clazz",
        "where clazz_id = #{clazzId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long clazzId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated Wed Apr 03 11:50:58 CST 2019
     */
    @Insert({
        "insert into t_clazz (clazz_id, class_name, ",
        "major_id, creator, ",
        "updater, version, ",
        "is_del, create_time, ",
        "update_time)",
        "values (#{clazzId,jdbcType=BIGINT}, #{className,jdbcType=VARCHAR}, ",
        "#{majorId,jdbcType=BIGINT}, #{creator,jdbcType=BIGINT}, ",
        "#{updater,jdbcType=BIGINT}, #{version,jdbcType=INTEGER}, ",
        "#{isDel,jdbcType=BIT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(TClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated Wed Apr 03 11:50:58 CST 2019
     */
    int insertSelective(TClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated Wed Apr 03 11:50:58 CST 2019
     */
    List<TClazz> selectByExample(TClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated Wed Apr 03 11:50:58 CST 2019
     */
    @Select({
        "select",
        "clazz_id, class_name, major_id, creator, updater, version, is_del, create_time, ",
        "update_time",
        "from t_clazz",
        "where clazz_id = #{clazzId,jdbcType=BIGINT}"
    })
    @ResultMap("org.exam.mapper.TClazzMapper.BaseResultMap")
    TClazz selectByPrimaryKey(Long clazzId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated Wed Apr 03 11:50:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") TClazz record, @Param("example") TClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated Wed Apr 03 11:50:58 CST 2019
     */
    int updateByExample(@Param("record") TClazz record, @Param("example") TClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated Wed Apr 03 11:50:58 CST 2019
     */
    int updateByPrimaryKeySelective(TClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clazz
     *
     * @mbg.generated Wed Apr 03 11:50:58 CST 2019
     */
    @Update({
        "update t_clazz",
        "set class_name = #{className,jdbcType=VARCHAR},",
          "major_id = #{majorId,jdbcType=BIGINT},",
          "creator = #{creator,jdbcType=BIGINT},",
          "updater = #{updater,jdbcType=BIGINT},",
          "version = #{version,jdbcType=INTEGER},",
          "is_del = #{isDel,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where clazz_id = #{clazzId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TClazz record);
}