package org.exam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.exam.bean.entity.TDic;
import org.exam.bean.entity.TDicExample;

public interface TDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    long countByExample(TDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    int deleteByExample(TDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    @Delete({
        "delete from t_dic",
        "where dic_id = #{dicId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long dicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    @Insert({
        "insert into t_dic (dic_id, dic_key, ",
        "dic_value, dic_type_id, ",
        "is_del, create_time, ",
        "update_time, creator, ",
        "updater, version)",
        "values (#{dicId,jdbcType=BIGINT}, #{dicKey,jdbcType=VARCHAR}, ",
        "#{dicValue,jdbcType=VARCHAR}, #{dicTypeId,jdbcType=VARCHAR}, ",
        "#{isDel,jdbcType=BIT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{creator,jdbcType=BIGINT}, ",
        "#{updater,jdbcType=BIGINT}, #{version,jdbcType=INTEGER})"
    })
    int insert(TDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    int insertSelective(TDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    List<TDic> selectByExample(TDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    @Select({
        "select",
        "dic_id, dic_key, dic_value, dic_type_id, is_del, create_time, update_time, creator, ",
        "updater, version",
        "from t_dic",
        "where dic_id = #{dicId,jdbcType=BIGINT}"
    })
    @ResultMap("org.exam.mapper.TDicMapper.BaseResultMap")
    TDic selectByPrimaryKey(Long dicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") TDic record, @Param("example") TDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    int updateByExample(@Param("record") TDic record, @Param("example") TDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    int updateByPrimaryKeySelective(TDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    @Update({
        "update t_dic",
        "set dic_key = #{dicKey,jdbcType=VARCHAR},",
          "dic_value = #{dicValue,jdbcType=VARCHAR},",
          "dic_type_id = #{dicTypeId,jdbcType=VARCHAR},",
          "is_del = #{isDel,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=BIGINT},",
          "updater = #{updater,jdbcType=BIGINT},",
          "version = #{version,jdbcType=INTEGER}",
        "where dic_id = #{dicId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TDic record);
}