package org.exam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.exam.bean.entity.TDicType;
import org.exam.bean.entity.TDicTypeExample;

public interface TDicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_type
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    long countByExample(TDicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_type
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    int deleteByExample(TDicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_type
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    @Delete({
        "delete from t_dic_type",
        "where dic_type_id = #{dicTypeId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long dicTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_type
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    @Insert({
        "insert into t_dic_type (dic_type_id, dic_type_name, ",
        "is_del, create_time, ",
        "update_time, creator, ",
        "updater, version)",
        "values (#{dicTypeId,jdbcType=BIGINT}, #{dicTypeName,jdbcType=VARCHAR}, ",
        "#{isDel,jdbcType=BIT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{creator,jdbcType=BIGINT}, ",
        "#{updater,jdbcType=BIGINT}, #{version,jdbcType=INTEGER})"
    })
    int insert(TDicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_type
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    int insertSelective(TDicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_type
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    List<TDicType> selectByExample(TDicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_type
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    @Select({
        "select",
        "dic_type_id, dic_type_name, is_del, create_time, update_time, creator, updater, ",
        "version",
        "from t_dic_type",
        "where dic_type_id = #{dicTypeId,jdbcType=BIGINT}"
    })
    @ResultMap("org.exam.mapper.TDicTypeMapper.BaseResultMap")
    TDicType selectByPrimaryKey(Long dicTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_type
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") TDicType record, @Param("example") TDicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_type
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    int updateByExample(@Param("record") TDicType record, @Param("example") TDicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_type
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    int updateByPrimaryKeySelective(TDicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dic_type
     *
     * @mbg.generated Mon Apr 01 09:36:14 CST 2019
     */
    @Update({
        "update t_dic_type",
        "set dic_type_name = #{dicTypeName,jdbcType=VARCHAR},",
          "is_del = #{isDel,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=BIGINT},",
          "updater = #{updater,jdbcType=BIGINT},",
          "version = #{version,jdbcType=INTEGER}",
        "where dic_type_id = #{dicTypeId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TDicType record);
}