package org.exam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.exam.bean.entity.TExamPaper;
import org.exam.bean.entity.TExamPaperExample;

public interface TExamPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated Thu Apr 04 09:21:39 CST 2019
     */
    long countByExample(TExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated Thu Apr 04 09:21:39 CST 2019
     */
    int deleteByExample(TExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated Thu Apr 04 09:21:39 CST 2019
     */
    @Delete({
        "delete from t_exam_paper",
        "where paper_id = #{paperId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long paperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated Thu Apr 04 09:21:39 CST 2019
     */
    @Insert({
        "insert into t_exam_paper (paper_id, paper_name, ",
        "course_id, is_del, create_time, ",
        "update_time, creator, ",
        "updater, version)",
        "values (#{paperId,jdbcType=BIGINT}, #{paperName,jdbcType=VARCHAR}, ",
        "#{courseId,jdbcType=BIGINT}, #{isDel,jdbcType=BIT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{creator,jdbcType=INTEGER}, ",
        "#{updater,jdbcType=INTEGER}, #{version,jdbcType=INTEGER})"
    })
    int insert(TExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated Thu Apr 04 09:21:39 CST 2019
     */
    int insertSelective(TExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated Thu Apr 04 09:21:39 CST 2019
     */
    List<TExamPaper> selectByExample(TExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated Thu Apr 04 09:21:39 CST 2019
     */
    @Select({
        "select",
        "paper_id, paper_name, course_id, is_del, create_time, update_time, creator, ",
        "updater, version",
        "from t_exam_paper",
        "where paper_id = #{paperId,jdbcType=BIGINT}"
    })
    @ResultMap("org.exam.mapper.TExamPaperMapper.BaseResultMap")
    TExamPaper selectByPrimaryKey(Long paperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated Thu Apr 04 09:21:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") TExamPaper record, @Param("example") TExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated Thu Apr 04 09:21:39 CST 2019
     */
    int updateByExample(@Param("record") TExamPaper record, @Param("example") TExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated Thu Apr 04 09:21:39 CST 2019
     */
    int updateByPrimaryKeySelective(TExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated Thu Apr 04 09:21:39 CST 2019
     */
    @Update({
        "update t_exam_paper",
        "set paper_name = #{paperName,jdbcType=VARCHAR},",
          "course_id = #{courseId,jdbcType=BIGINT},",
          "is_del = #{isDel,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER},",
          "updater = #{updater,jdbcType=INTEGER},",
          "version = #{version,jdbcType=INTEGER}",
        "where paper_id = #{paperId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TExamPaper record);
}