package org.exam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.exam.bean.entity.TExamine;
import org.exam.bean.entity.TExamineExample;

public interface TExamineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbg.generated Thu Apr 04 09:22:40 CST 2019
     */
    long countByExample(TExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbg.generated Thu Apr 04 09:22:40 CST 2019
     */
    int deleteByExample(TExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbg.generated Thu Apr 04 09:22:40 CST 2019
     */
    @Delete({
        "delete from t_examine",
        "where examine_id = #{examineId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long examineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbg.generated Thu Apr 04 09:22:40 CST 2019
     */
    @Insert({
        "insert into t_examine (examine_id, examine_name, ",
        "paper_id, start_time, ",
        "end_time, is_del, create_time, ",
        "update_time, creator, ",
        "updater, version)",
        "values (#{examineId,jdbcType=BIGINT}, #{examineName,jdbcType=VARCHAR}, ",
        "#{paperId,jdbcType=BIGINT}, #{startTime,jdbcType=TIMESTAMP}, ",
        "#{endTime,jdbcType=TIMESTAMP}, #{isDel,jdbcType=BIT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{creator,jdbcType=INTEGER}, ",
        "#{updater,jdbcType=INTEGER}, #{version,jdbcType=INTEGER})"
    })
    int insert(TExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbg.generated Thu Apr 04 09:22:40 CST 2019
     */
    int insertSelective(TExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbg.generated Thu Apr 04 09:22:40 CST 2019
     */
    List<TExamine> selectByExample(TExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbg.generated Thu Apr 04 09:22:40 CST 2019
     */
    @Select({
        "select",
        "examine_id, examine_name, paper_id, start_time, end_time, is_del, create_time, ",
        "update_time, creator, updater, version",
        "from t_examine",
        "where examine_id = #{examineId,jdbcType=BIGINT}"
    })
    @ResultMap("org.exam.mapper.TExamineMapper.BaseResultMap")
    TExamine selectByPrimaryKey(Long examineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbg.generated Thu Apr 04 09:22:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") TExamine record, @Param("example") TExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbg.generated Thu Apr 04 09:22:40 CST 2019
     */
    int updateByExample(@Param("record") TExamine record, @Param("example") TExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbg.generated Thu Apr 04 09:22:40 CST 2019
     */
    int updateByPrimaryKeySelective(TExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbg.generated Thu Apr 04 09:22:40 CST 2019
     */
    @Update({
        "update t_examine",
        "set examine_name = #{examineName,jdbcType=VARCHAR},",
          "paper_id = #{paperId,jdbcType=BIGINT},",
          "start_time = #{startTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "is_del = #{isDel,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER},",
          "updater = #{updater,jdbcType=INTEGER},",
          "version = #{version,jdbcType=INTEGER}",
        "where examine_id = #{examineId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TExamine record);
}