package org.exam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.exam.bean.entity.TMajor;
import org.exam.bean.entity.TMajorExample;

public interface TMajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    long countByExample(TMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    int deleteByExample(TMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    @Delete({
        "delete from t_major",
        "where major_id = #{majorId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long majorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    @Insert({
        "insert into t_major (major_id, major_name, ",
        "academy_id, creator, ",
        "updater, version, ",
        "is_del, create_time, ",
        "update_time)",
        "values (#{majorId,jdbcType=BIGINT}, #{majorName,jdbcType=VARCHAR}, ",
        "#{academyId,jdbcType=BIGINT}, #{creator,jdbcType=BIGINT}, ",
        "#{updater,jdbcType=BIGINT}, #{version,jdbcType=INTEGER}, ",
        "#{isDel,jdbcType=BIT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(TMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    int insertSelective(TMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    List<TMajor> selectByExample(TMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    @Select({
        "select",
        "major_id, major_name, academy_id, creator, updater, version, is_del, create_time, ",
        "update_time",
        "from t_major",
        "where major_id = #{majorId,jdbcType=BIGINT}"
    })
    @ResultMap("org.exam.mapper.TMajorMapper.TreeResultMap")
    TMajor selectByPrimaryKey(Long majorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") TMajor record, @Param("example") TMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    int updateByExample(@Param("record") TMajor record, @Param("example") TMajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    int updateByPrimaryKeySelective(TMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_major
     *
     * @mbg.generated Wed Apr 03 11:42:34 CST 2019
     */
    @Update({
        "update t_major",
        "set major_name = #{majorName,jdbcType=VARCHAR},",
          "academy_id = #{academyId,jdbcType=BIGINT},",
          "creator = #{creator,jdbcType=BIGINT},",
          "updater = #{updater,jdbcType=BIGINT},",
          "version = #{version,jdbcType=INTEGER},",
          "is_del = #{isDel,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where major_id = #{majorId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TMajor record);
}