package org.exam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.exam.bean.entity.TMenu;
import org.exam.bean.entity.TMenuExample;

public interface TMenuMapper {
    List<TMenu> getAllMenu();
    List<TMenu> getMenuByParentId(Long parentId);

    /**
     * home页菜单树
     * @return
     */
    List<TMenu> getMenuByUserIdAndParentId(@Param(value = "userId") Long userId,
                                           @Param(value = "parentId") Long parentId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sun Mar 31 18:05:05 CST 2019
     */
    long countByExample(TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sun Mar 31 18:05:05 CST 2019
     */
    int deleteByExample(TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sun Mar 31 18:05:05 CST 2019
     */
    @Delete({
        "delete from t_menu",
        "where menu_id = #{menuId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sun Mar 31 18:05:05 CST 2019
     */
    @Insert({
        "insert into t_menu (menu_id, url, ",
        "path, component, ",
        "name, icon_cls, parent_id, ",
        "creator, updater, ",
        "version, is_del, create_time, ",
        "update_time, sort)",
        "values (#{menuId,jdbcType=BIGINT}, #{url,jdbcType=VARCHAR}, ",
        "#{path,jdbcType=VARCHAR}, #{component,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{iconCls,jdbcType=VARCHAR}, #{parentId,jdbcType=BIGINT}, ",
        "#{creator,jdbcType=BIGINT}, #{updater,jdbcType=BIGINT}, ",
        "#{version,jdbcType=INTEGER}, #{isDel,jdbcType=BIT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{sort,jdbcType=TINYINT})"
    })
    int insert(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sun Mar 31 18:05:05 CST 2019
     */
    int insertSelective(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sun Mar 31 18:05:05 CST 2019
     */
    List<TMenu> selectByExample(TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sun Mar 31 18:05:05 CST 2019
     */
    @Select({
        "select",
        "menu_id, url, path, component, name, icon_cls, parent_id, creator, updater, ",
        "version, is_del, create_time, update_time, sort",
        "from t_menu",
        "where menu_id = #{menuId,jdbcType=BIGINT}"
    })
    @ResultMap("org.exam.mapper.TMenuMapper.BaseResultMap")
    TMenu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sun Mar 31 18:05:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") TMenu record, @Param("example") TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sun Mar 31 18:05:05 CST 2019
     */
    int updateByExample(@Param("record") TMenu record, @Param("example") TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sun Mar 31 18:05:05 CST 2019
     */
    int updateByPrimaryKeySelective(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Sun Mar 31 18:05:05 CST 2019
     */
    @Update({
        "update t_menu",
        "set url = #{url,jdbcType=VARCHAR},",
          "path = #{path,jdbcType=VARCHAR},",
          "component = #{component,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "icon_cls = #{iconCls,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=BIGINT},",
          "creator = #{creator,jdbcType=BIGINT},",
          "updater = #{updater,jdbcType=BIGINT},",
          "version = #{version,jdbcType=INTEGER},",
          "is_del = #{isDel,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "sort = #{sort,jdbcType=TINYINT}",
        "where menu_id = #{menuId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TMenu record);
}