package org.exam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.exam.bean.entity.TPaperQuestion;
import org.exam.bean.entity.TPaperQuestionExample;

public interface TPaperQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_question
     *
     * @mbg.generated Fri May 17 08:47:47 CST 2019
     */
    long countByExample(TPaperQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_question
     *
     * @mbg.generated Fri May 17 08:47:47 CST 2019
     */
    int deleteByExample(TPaperQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_question
     *
     * @mbg.generated Fri May 17 08:47:47 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_question
     *
     * @mbg.generated Fri May 17 08:47:47 CST 2019
     */
    int insert(TPaperQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_question
     *
     * @mbg.generated Fri May 17 08:47:47 CST 2019
     */
    int insertSelective(TPaperQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_question
     *
     * @mbg.generated Fri May 17 08:47:47 CST 2019
     */
    List<TPaperQuestion> selectByExample(TPaperQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_question
     *
     * @mbg.generated Fri May 17 08:47:47 CST 2019
     */
    TPaperQuestion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_question
     *
     * @mbg.generated Fri May 17 08:47:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") TPaperQuestion record, @Param("example") TPaperQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_question
     *
     * @mbg.generated Fri May 17 08:47:47 CST 2019
     */
    int updateByExample(@Param("record") TPaperQuestion record, @Param("example") TPaperQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_question
     *
     * @mbg.generated Fri May 17 08:47:47 CST 2019
     */
    int updateByPrimaryKeySelective(TPaperQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper_question
     *
     * @mbg.generated Fri May 17 08:47:47 CST 2019
     */
    int updateByPrimaryKey(TPaperQuestion record);
}