package org.exam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.exam.bean.entity.TQuestionJudge;
import org.exam.bean.entity.TQuestionJudgeExample;

public interface TQuestionJudgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    long countByExample(TQuestionJudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    int deleteByExample(TQuestionJudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    @Delete({
        "delete from t_question_judge",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    @Insert({
        "insert into t_question_judge (id, judge_no, ",
        "judge_name, answer, is_del, ",
        "create_time, update_time, ",
        "creator, updater, ",
        "version)",
        "values (#{id,jdbcType=BIGINT}, #{judgeNo,jdbcType=BIGINT}, ",
        "#{judgeName,jdbcType=VARCHAR}, #{answer,jdbcType=BIT}, #{isDel,jdbcType=BIT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=INTEGER}, #{updater,jdbcType=INTEGER}, ",
        "#{version,jdbcType=INTEGER})"
    })
    int insert(TQuestionJudge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    int insertSelective(TQuestionJudge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    List<TQuestionJudge> selectByExample(TQuestionJudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    @Select({
        "select",
        "id, judge_no, judge_name, answer, is_del, create_time, update_time, creator, ",
        "updater, version",
        "from t_question_judge",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("org.exam.mapper.TQuestionJudgeMapper.BaseResultMap")
    TQuestionJudge selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") TQuestionJudge record, @Param("example") TQuestionJudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    int updateByExample(@Param("record") TQuestionJudge record, @Param("example") TQuestionJudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    int updateByPrimaryKeySelective(TQuestionJudge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    @Update({
        "update t_question_judge",
        "set judge_no = #{judgeNo,jdbcType=BIGINT},",
          "judge_name = #{judgeName,jdbcType=VARCHAR},",
          "answer = #{answer,jdbcType=BIT},",
          "is_del = #{isDel,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER},",
          "updater = #{updater,jdbcType=INTEGER},",
          "version = #{version,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TQuestionJudge record);
}