package org.exam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.exam.bean.entity.TQuestionJudge;
import org.exam.bean.entity.TQuestionJudgeExample;

public interface TQuestionJudgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    long countByExample(TQuestionJudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    int deleteByExample(TQuestionJudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    @Delete({
        "delete from t_question_judge",
        "where judge_id = #{judgeId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long judgeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    @Insert({
        "insert into t_question_judge (judge_id, judge_name, ",
        "answer, course_id, is_del, ",
        "create_time, update_time, ",
        "creator, updater, ",
        "version)",
        "values (#{judgeId,jdbcType=BIGINT}, #{judgeName,jdbcType=VARCHAR}, ",
        "#{answer,jdbcType=BIT}, #{courseId,jdbcType=BIGINT}, #{isDel,jdbcType=BIT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=INTEGER}, #{updater,jdbcType=INTEGER}, ",
        "#{version,jdbcType=INTEGER})"
    })
    int insert(TQuestionJudge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    int insertSelective(TQuestionJudge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    List<TQuestionJudge> selectByExample(TQuestionJudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    @Select({
        "select",
        "judge_id, judge_name, answer, course_id, is_del, create_time, update_time, creator, ",
        "updater, version",
        "from t_question_judge",
        "where judge_id = #{judgeId,jdbcType=BIGINT}"
    })
    @ResultMap("org.exam.mapper.TQuestionJudgeMapper.BaseResultMap")
    TQuestionJudge selectByPrimaryKey(Long judgeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") TQuestionJudge record, @Param("example") TQuestionJudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    int updateByExample(@Param("record") TQuestionJudge record, @Param("example") TQuestionJudgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    int updateByPrimaryKeySelective(TQuestionJudge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_judge
     *
     * @mbg.generated Thu Apr 04 09:19:16 CST 2019
     */
    @Update({
        "update t_question_judge",
        "set judge_name = #{judgeName,jdbcType=VARCHAR},",
          "answer = #{answer,jdbcType=BIT},",
          "course_id = #{courseId,jdbcType=BIGINT},",
          "is_del = #{isDel,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER},",
          "updater = #{updater,jdbcType=INTEGER},",
          "version = #{version,jdbcType=INTEGER}",
        "where judge_id = #{judgeId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TQuestionJudge record);
}