package org.exam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.exam.bean.entity.TQuestionShortAnswer;
import org.exam.bean.entity.TQuestionShortAnswerExample;

public interface TQuestionShortAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_short_answer
     *
     * @mbg.generated Mon Apr 29 20:20:44 CST 2019
     */
    long countByExample(TQuestionShortAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_short_answer
     *
     * @mbg.generated Mon Apr 29 20:20:44 CST 2019
     */
    int deleteByExample(TQuestionShortAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_short_answer
     *
     * @mbg.generated Mon Apr 29 20:20:44 CST 2019
     */
    int deleteByPrimaryKey(Long shortAnswerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_short_answer
     *
     * @mbg.generated Mon Apr 29 20:20:44 CST 2019
     */
    int insert(TQuestionShortAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_short_answer
     *
     * @mbg.generated Mon Apr 29 20:20:44 CST 2019
     */
    int insertSelective(TQuestionShortAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_short_answer
     *
     * @mbg.generated Mon Apr 29 20:20:44 CST 2019
     */
    List<TQuestionShortAnswer> selectByExample(TQuestionShortAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_short_answer
     *
     * @mbg.generated Mon Apr 29 20:20:44 CST 2019
     */
    TQuestionShortAnswer selectByPrimaryKey(Long shortAnswerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_short_answer
     *
     * @mbg.generated Mon Apr 29 20:20:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") TQuestionShortAnswer record, @Param("example") TQuestionShortAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_short_answer
     *
     * @mbg.generated Mon Apr 29 20:20:44 CST 2019
     */
    int updateByExample(@Param("record") TQuestionShortAnswer record, @Param("example") TQuestionShortAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_short_answer
     *
     * @mbg.generated Mon Apr 29 20:20:44 CST 2019
     */
    int updateByPrimaryKeySelective(TQuestionShortAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_short_answer
     *
     * @mbg.generated Mon Apr 29 20:20:44 CST 2019
     */
    int updateByPrimaryKey(TQuestionShortAnswer record);
}