package org.exam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.exam.bean.entity.TQuestionChoice;
import org.exam.bean.entity.TQuestionChoiceExample;

public interface TQuestionChoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Sat Mar 30 15:26:07 CST 2019
     */
    long countByExample(TQuestionChoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Sat Mar 30 15:26:07 CST 2019
     */
    int deleteByExample(TQuestionChoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Sat Mar 30 15:26:07 CST 2019
     */
    @Delete({
        "delete from t_question_choice",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Sat Mar 30 15:26:07 CST 2019
     */
    @Insert({
        "insert into t_question_choice (id, choice_no, ",
        "choice_name, choice_type, ",
        "option_a, option_b, ",
        "option_c, option_d, ",
        "single_answer, multi_answer, ",
        "is_del, create_time, ",
        "update_time, creator, ",
        "updater, version)",
        "values (#{id,jdbcType=BIGINT}, #{choiceNo,jdbcType=BIGINT}, ",
        "#{choiceName,jdbcType=VARCHAR}, #{choiceType,jdbcType=BIT}, ",
        "#{optionA,jdbcType=VARCHAR}, #{optionB,jdbcType=VARCHAR}, ",
        "#{optionC,jdbcType=VARCHAR}, #{optionD,jdbcType=VARCHAR}, ",
        "#{singleAnswer,jdbcType=CHAR}, #{multiAnswer,jdbcType=VARCHAR}, ",
        "#{isDel,jdbcType=BIT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{creator,jdbcType=INTEGER}, ",
        "#{updater,jdbcType=INTEGER}, #{version,jdbcType=INTEGER})"
    })
    int insert(TQuestionChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Sat Mar 30 15:26:07 CST 2019
     */
    int insertSelective(TQuestionChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Sat Mar 30 15:26:07 CST 2019
     */
    List<TQuestionChoice> selectByExample(TQuestionChoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Sat Mar 30 15:26:07 CST 2019
     */
    @Select({
        "select",
        "id, choice_no, choice_name, choice_type, option_a, option_b, option_c, option_d, ",
        "single_answer, multi_answer, is_del, create_time, update_time, creator, updater, ",
        "version",
        "from t_question_choice",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("org.exam.mapper.TQuestionChoiceMapper.BaseResultMap")
    TQuestionChoice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Sat Mar 30 15:26:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") TQuestionChoice record, @Param("example") TQuestionChoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    int updateByExample(@Param("record") TQuestionChoice record, @Param("example") TQuestionChoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    int updateByPrimaryKeySelective(TQuestionChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question_choice
     *
     * @mbg.generated Sat Mar 30 15:26:08 CST 2019
     */
    @Update({
        "update t_question_choice",
        "set choice_no = #{choiceNo,jdbcType=BIGINT},",
          "choice_name = #{choiceName,jdbcType=VARCHAR},",
          "choice_type = #{choiceType,jdbcType=BIT},",
          "option_a = #{optionA,jdbcType=VARCHAR},",
          "option_b = #{optionB,jdbcType=VARCHAR},",
          "option_c = #{optionC,jdbcType=VARCHAR},",
          "option_d = #{optionD,jdbcType=VARCHAR},",
          "single_answer = #{singleAnswer,jdbcType=CHAR},",
          "multi_answer = #{multiAnswer,jdbcType=VARCHAR},",
          "is_del = #{isDel,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=INTEGER},",
          "updater = #{updater,jdbcType=INTEGER},",
          "version = #{version,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TQuestionChoice record);
}